set nocompatible "required for vundle
filetype off "required for vundle


" rtp (runtimepaths) is a list of comma seperated paths, the first 
" of which is the vimfiles directory
let $VIMFILESDIR=split(&rtp, ",")[0]

let $VIMTIPS="$VIMFILESDIR/vimtips.md"

set rtp+=$VIMFILESDIR/bundle/Vundle.vim

call vundle#begin('$VIMFILESDIR/bundle/')
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'             " Git wrapper plugin
Plugin 'sjl/badwolf'                    " Colour scheme
Plugin 'ctrlpvim/ctrlp.vim'             " Fuzzy search for files etc.
Plugin 'vim-airline/vim-airline'        " powerline style plugin in pure vimscript
Plugin 'scrooloose/nerdtree'            " Tree based navigation of filesystem
call vundle#end()

filetype plugin indent on " required by vundle

" Make the ctrlp plugin display up to 100 results rather than the default of
" 10
let g:ctrlp_match_window = 'results:100'

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab " tabs are spaces
set smarttab
set ignorecase " ignore case when searching
set smartcase
set laststatus=2    "Always display the status bar.

set number " enable line numbers
syntax on " syntax highlighting
colorscheme badwolf
set cursorline " highlight current line
set wildmenu " graphical auto-complete menu for tab completion
set showmatch " highlight matching parentheses
set hlsearch " highlight search matches

autocmd BufRead,BufNewFile  *.txt setlocal tw=80
autocmd BufRead,BufNewFile  *.txt setlocal spell spelllang=en_gb

" Make backspace behave correctly.
set backspace=indent,eol,start

if has("win32")
    set guifont=Consolas:h10
else
    set guifont=Inconsolata\ 9
endif

" Open explorer window for the path containing the current file.
map <C-e> :!start explorer %:p:h:gs?\/?\\\\\\?<CR>
